### ISSUE TITLE
can't run with vmware

### ISSUE THREAD

**Issue by scholdborg** [eaksel/packer-Debian10#1]
Hi, I'm trying to run with "packer build -only=vmware-iso debian10.json" but I get this error:

packer build -only=vmware-iso debian10.json
vmware-iso: output will be in this color.

1 error occurred:
        * unknown configuration key: "ssh_wait_timeout"; raws is []interface {}{map[string]interface {}{"boot_command":[]interface {}{"<esc><wait>", "auto ", "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<wait>", "<enter>"}, "boot_wait":"5s", "disk_size":"40960", "disk_type_id":"0", "guest_os_type":"debian10-64", "headless":false, "http_directory":"http", "iso_checksum":"6a901b5abe43d88b39d627e1339d15507cc38f980036b928f835e0f0e957d3d8", "iso_checksum_type":"sha256", "iso_url":"https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.3.0-amd64-netinst.iso", "shutdown_command":"echo 'packer'|sudo -S shutdown -P now", "ssh_password":"packer", "ssh_port":22, "ssh_username":"packer", "ssh_wait_timeout":"10000s", "vm_name":"debian-10.3.0-amd64", "vmx_data":map[interface {}]interface {}{"memsize":"1024", "numvcpus":"1", "virtualHW.version":"14"}}, map[string]interface {}{"packer_build_name":"vmware-iso", "packer_builder_type":"vmware-iso", "packer_debug":false, "packer_force":false, "packer_on_error":"", "packer_template_path":"D:\\Work\\packer-Debian10\\debian10.json", "packer_user_variables":map[interface {}]interface {}{"boot_wait":"5s", "disk_size":"40960", "iso_checksum":"6a901b5abe43d88b39d627e1339d15507cc38f980036b928f835e0f0e957d3d8", "iso_checksum_type":"sha256", "iso_url":"https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.3.0-amd64-netinst.iso", "memsize":"1024", "numvcpus":"1", "ssh_password":"packer", "ssh_username":"packer", "vm_name":"debian-10.3.0-amd64"}}}

 and ctx data is map[interface {}]interface {}(nil)

-----------------------

I have vmware workstation installed, tried running from both Windows10 / Debian10 but same error, works with virtualbox though.

**Comment by eaksel** [comment]
Hi scholdborg,

Thank you for reporting the issue and sorry for the delay.

I've looked a the issue, seems like the "ssh_wait_timeout" option was recently removed from the vmware-iso provisioner. I was using Packer 1.5.1 without issue, tried the latest version (1.5.5) and i'm getting the same error.

I'll look more into the issue as soon as I have some time.

**Comment by eaksel** [comment]
Hi scholdborg,

I've changed the `"ssh_wait_timeout"` option with `"ssh_timeout"` in the "builders" section, tested it with Packer 1.5.5 and VMware Workstation 15.5.2 build-15785246. Seems to be working fine now.

If that's also the case for you feel free to close the issue.
