### ISSUE TITLE
variable iso_checksum_type does not exist anymore

### ISSUE THREAD

**Issue by coveritytest** [eaksel/packer-Debian10#2]
packer build fails because iso_checksum_type does not exist anymore. you can remove iso_checksum_type as packer recognizes the type automatically. tested with latest version 1.6.2.

**Comment by eaksel** [comment]
Hi coveritytest,

Thanks for the info, I've removed 'iso_checksum_type' from the config file, everything is back to normal.

If this also works for you, feel free to close the issue.

**Comment by hacklab808** [comment]
For what it is worth, there may be some people on older versions of Packer. I, for instance, was running Packer 1.3.4 on a system. So, I had to insert:

"iso_checksum_type": "sha256",
 and
"iso_checksum_type": "{{user `iso_checksum_type`}}",

in appropriate sections of debian10.json

**Comment by eaksel** [comment]
Hi hacklab808,

That's indeed something to be aware of.

I think that it would be best if the configuration files are compatible with the latest version of Packer.

**Comment by coveritytest** [comment]
Thanks for the quick fix.
