### ISSUE TITLE
Cannot build two VM's simultaneously

### ISSUE THREAD

**Issue by Erriez** [eaksel/packer-Debian10#8]
Default build directory is `output-BUILDNAME`. Starting to concurrent builds results in an error message:  
`Build 'virtualbox-iso' errored after 831 milliseconds 807 microseconds: Output directory exists: output-virtualbox-iso`.

I can provide a MR to address this, but previous reported issues and pull requests needs to be merged first.

**Comment by eaksel** [comment]
Hi @Erriez,

That'd be great, I'd gladly merge it.

**Comment by Erriez** [comment]
I've added `"output_directory": "output-{{ user `vm_name` }}"` to the VirtualBox `builders` section and solved the problem to build debian10 and debian11 simultaneously. Then it creates separate output directories. Thanks!

**Comment by Erriez** [comment]
No longer an issue when using separate repositories as mentioned in #9.
