### ISSUE TITLE
Feature request: Add Debian 11 Bullseye

### ISSUE THREAD

**Issue by Erriez** [eaksel/packer-Debian10#9]
Add configuration for Debian 11 Bullseye.

I already have this up and running and can provide a MR, but previous reported issues and pull requests needs to be merged first.

**Comment by eaksel** [comment]
Hi @Erriez,

I prefer keeping the repositories separated.
You can find Debian 11 here: https://github.com/eaksel/packer-Debian11

**Comment by Erriez** [comment]
Oh I was not aware of this repository. Thanks for you hint. Maybe an idea to mention this in the `README.md`? I also discovered `https://github.com/eaksel/packer-Win10` which is useful for me.
